gin:
  port: :6060
  debug: true
  gzip: false

jwt:
  expirein: 86400 

cors:
  enable: true

mysql:
  host: {{.MysqlConfig.Addr}}
  user: {{.MysqlConfig.User}}
  password: {{.MysqlConfig.Passwd}}
  db: {{.MysqlConfig.DBName}}

meta:
  logo: {{.ProjectName}}
  title: {{.ProjectName}}
